server:
  port: 8002
# sa-token配置
sa-token:
  # SSO-相关配置
  sso:
    # SSO-Server端-单点登录授权地址
    auth-url: http://sso.stp.com:9000/sso/auth
    # SSO-Server端-单点注销地址
    slo-url: http://sso.stp.com:9000/sso/logout

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  application:
    name: gateway-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.69.48:3306/mall_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(F7sPGHUiad/0t9Qm8YYtFsqSggCWNL34)
  redis:
    host: 120.26.69.48
    port: 6379
    password: ENC(F7sPGHUiad/0t9Qm8YYtFsqSggCWNL34)
    database: 1
    timeout: 10s

    jedis:
      pool:
        # 连接池最大连接数 默认值8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.69.48:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #文件微服务
        - id: mall_file_route
          uri: lb://file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1
        #商品微服务
        - id: mall_goods_route
          # lb：使用LoadBalancerClient实现负载均衡，后面goods是微服务名称[主要应用于集群环境]
          uri: lb://goods
          predicates:
            - Path=/api/album/**,/api/brand/**,/api/category/**,/api/categoryBrand/**,/api/para/**,/api/pref/**,/api/spec/**,/api/stockBack/**,/api/spu/**,/api/sku/**,/api/template/**,/api/undoLog/**
          filters:
            # 去掉路径中的第一个名称 如: /api/brand -> /brand
            - StripPrefix=1

        # 订单服务
        - id: mall_order
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
        #用户微服务
        - id: mall_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        # 认证服务
        - id: mall_auth_route
          uri: lb://sso-server
          predicates:
            - Path=/api/sso/**
          filters:
            - StripPrefix=1
        # 系统用户
        - id: mall_system_route
          uri: lb://system
          predicates:
            - Path=/api/admin/**,/api/role/**,/api/roleAdmin/**,/api/menu/**,/api/roleMenu/**
          filters:
            - StripPrefix=1
        # 物流微服务
        - id: mall_shipping_route
          uri: lb://shipping
          predicates:
            - Path=/api/shipping/**
          filters:
            - StripPrefix=1