server:
  port: 18083
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  application:
    name: search
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: 120.26.69.48:8848
# 配置该微服务只能通过网关访问
server-protect:
  onlyFetchByGateway: false
#feign:
#  hystrix:
#    enabled: true
##超时配置
#ribbon:
#  ReadTimeout: 300000
#  ConnectTimeout: 60000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000