# 端口
server:
  port: 9000

# Sa-Token 配置
sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  cookie:
    # 配置Cookie作用域
    domain: 127.0.0.1

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  application:
    name: sso-server
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.69.48:8848
  # Redis配置 （SSO模式一和模式二使用Redis来同步会话）
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 120.26.69.48
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ENC(F7sPGHUiad/0t9Qm8YYtFsqSggCWNL34)

    jedis:
      pool:
        # 连接池最大连接数 默认值8
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0